name: Build .abapgit.xml file
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out this repository
      uses: actions/checkout@v2
    - name: Create .abapgit.xml contents
      run: |
        abapitems=$(ls -1Ap abap | grep -v 'src/' | sed 's,^,    <item>/abap/,; s,$,</item>,')
        mainitems=$(ls -1Ap | grep -vE '(\.abapgit.xml|\.git\/)$' | sed 's,^,    <item>/,; s,$,</item>,')
        cat <<EOF
        <?xml version="1.0" encoding="utf-8"?>
        <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
         <asx:values>
          <DATA>
           <MASTER_LANGUAGE>E</MASTER_LANGUAGE>
           <STARTING_FOLDER>/abap/src/</STARTING_FOLDER>
           <FOLDER_LOGIC>PREFIX</FOLDER_LOGIC>
           <IGNORE>
        $abapitems
        $mainitems
           </IGNORE>
          </DATA>
         </asx:values>
        </asx:abap>
        EOF
