name: Conditional test

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Send greeting
        run: 'true'
      
      - name: Conditional
        if: ${{ success() }}
        run: echo Successful
