name: Check for disallowed content

on:
  pull_request:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

      - id: a
        env:
          GITHUBCONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUBCONTEXT"

      - id: check_files_changed
        name: Checks if disallowed content has been changed
        uses: dorny/paths-filter@v2
        with:
          list-files: 'shell'
          filters: |
            disallowed:
              - '!docs/**'

      - id: checkout
        name: Check out the repo
        if: steps.check_files_changed.outputs.disallowed == 'true'
        uses: actions/checkout@v2

      - id: auth_gh
        name: Authenticate gh to repo
        if: steps.check_files_changed.outputs.disallowed == 'true'
        run: echo -n ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - id: comment_on_disallowed
        if: steps.check_files_changed.outputs.disallowed == 'true'
        env:
          DISALLOWED_FILES: ${{ steps.check_files_changed.outputs.disallowed_files }}
        run: |
          printf "Hi there. It looks like you've modified some files in this repository that we can't accept in a contribution. Only actual documentation content, which is managed in the docs directory, is open for contribution.\n\nThe disallowed files that you submitted are:\n\n$DISALLOWED_FILES" \
          | gh pr comment ${{ github.event.pull_request.number }} --body-file -
          exit 1
