# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Show first few lines of README
        run: head README.md
        
      - name: Send greeting
        run: echo "Hello world"
      
      - name: Append line to README.md
        run: echo "- `date`" >> README.md
    
      - name: Check for changes (fails if no changes)
        run: ! git diff --quiet
        
      - name: Commit change
        if: ${{ success() }}
        run: |
          git config --global user.email "qmacro-bot@example.com"
          git config --global user.name "qmacro bot"
          git add README.md
          git commit -m 'add new date entry' || exit 0
          git push
        
      
      
