name: Markdown checks

on:
  pull_request:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - run: tree -I .git

    - run: tree -d

    - run: "echo ::add-matcher::.qmacro/workflows/markdownlint-problem-matcher.json"

    - run: |
        npm install \
          --no-package-lock \
          --no-save \
          markdownlint-cli markdownlint-rule-titlecase

    - run: npx markdownlint docs/ --rules markdownlint-rule-titlecase
