#######################################################################
### This workflow pushes changes back to an internal mirror of this ###
### repository, when changes are pushed to the main branch.         ###
### This workflow must be run from within the source repo.          ###
#######################################################################


name: push-internal

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push:
    name: Push changes to remote (internal) repository
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: github-actions
      GIT_USER_EMAIL: github-action@sap.com
      INT_REPO_TOKEN: ${{ secrets.INT_PAT }}
      INT_REPO_HOST: github.tools.sap
      INT_OWNER_REPO: coDoc/test
      INT_REMOTE_NAME: internal
      BRANCH: master

    steps:

      - name: Context
        run: echo ${{ toJSON(github) }}

      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: Add git configuration
        id: config
        run: |
          git config --local user.name ${{ env.GIT_USER_NAME }}
          git config --local user.email ${{ env.GIT_USER_EMAIL }}

      - name: Push to internal
        id: push
        run: |
          git remote add ${{ env.INT_REMOTE_NAME}} https://x-access-token:${{ env.INT_REPO_TOKEN }}@${{ env.INT_REPO_HOST }}/${{ env.INT_OWNER_REPO }}.git
          git pull ${{ env.INT_REMOTE_NAME }} ${{ env.BRANCH }} --allow-unrelated-histories
          git push ${{ env.INT_REMOTE_NAME }} ${{ env.BRANCH }}
