name: Secret test

on:
  pull_request:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - id: auth_gh
        name: Authentiate gh to repo
        run: echo -n ${{ secrets.SAPDOCS_Q_PAT_REPO_READORG }} | gh auth login --with-token

      - id: check_membership
        name: Check team membership of PR author
        env:
          team: 'admin'
        run: |
          IFS='/' read -r owner repository <<< "$GITHUB_REPOSITORY"
          gh api "/orgs/$owner/teams/${repository}-${team}/memberships/$GITHUB_ACTOR"
