name: Update README test

on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Show first few lines of README
        run: head README.md
        
      - name: Send greeting
        run: echo "Hello world"
    
      - name: Check for changes (fails if no changes)
        run: |
          ! git diff --quiet
        
      - name: Commit change
        if: ${{ success() }}
        run: |
          git config --global user.email "qmacro-bot@example.com"
          git config --global user.name "qmacro bot"
          git add README.md
          git commit -m 'add new date entry' || exit 0
          git push
        
      
      
